### PR TITLE
feat: remove prettier

### PR DESCRIPTION
**Pull request by damontgomery**
Removes prettier.

## Testing notes

`yarn install`, `yarn start`, `yarn lint`, others?

## Notes

`yarn remove prettier eslint-config-prettier`

<a href="https://gitpod.io/#https://github.com/phase2/outline/pull/208"></a>

### CODE REVIEW

**Comment by damontgomery** [comment]
Got too excited. Going to do better search.

**Comment by himerus** [comment]
Marking this as `Needs: Discussion`, and marking as Draft until we can go over it a bit more in detail, and discuss the ramifications and or alternative options a bit further. Tomorrow's working hours hopefully?

This will help make sure it isn't "accidentally" merged.

**Comment by damontgomery** [comment]
> Marking this as `Needs: Discussion`, and marking as Draft until we can go over it a bit more in detail, and discuss the ramifications and or alternative options a bit further. Tomorrow's working hours hopefully?
> 
> This will help make sure it isn't "accidentally" merged.

Sounds good! I think this catches all the things, but would be good for people to give it a go and see what they think.

Worst case scenario, you can revert the commit and run prettier. :)

**Comment by himerus** [comment]
Postponing for future discussion.

**Pull request closed without merging**
