### PR TITLE
#236: Adding in mobile controller and CSS config changes to Outline Heading

### PR DESCRIPTION
**Pull request by sarahp**
**Developer Notes**
Adding in the `mobile controller` and CSS config changes into Outline Heading. Implements Issue #236  

**Testing Notes**
1. Go to Storybook
2. Go to the Heading component
3. Size the screen up and down
4. Observe that the text gets smaller at smaller screens and larger at larger screens

<a href="https://gitpod.io/#https://github.com/phase2/outline/pull/237"></a>

### CODE REVIEW

**Comment by himerus** [comment]
Holding this one until we see the full impact and any issues with these changes on an internal client project. I think we may have a few small adjustments to make here.

**Comment by shaal** [comment]
@sarahp I'd love to understand this feature better.
Aren't heading display sizes very specific in each project?
What does the mobile controller do?

**Comment by sarahp** [comment]
> @sarahp I'd love to understand this feature better. Aren't heading display sizes very specific in each project? What does the mobile controller do?

The mobile controller applies where to break. This doesn't change the sizes of the `h1-h6` or the `levels`, just sets the sizes to use a smaller `level` or `h-tag` when the screen gets smaller.

**Comment by himerus** [comment]
Updated with various cleanup, better usage of all 3 sizes on `<outline-heading>` elements that only use the `level` attribute and omit the `level-size` one.

**Pull request merged**
