### PR TITLE
Storybook Deprecation Cleanup

### PR DESCRIPTION
**Pull request by himerus**
Fixing a list of issues preventing any upgrade to Storybook 7.0. 
This just reduces the warnings in the console as well as prepare all our stories to be built correctly. 

See:

- https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-controloptions
- https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args
- https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports

<a href="https://gitpod.io/#https://github.com/phase2/outline/pull/195"></a>

### CODE REVIEW

**Review by mabry1985 — APPROVED** [review]

**Review by grshane — CHANGES_REQUESTED** [review]
What's with all of the commented out lines?

**Comment by mabry1985** [comment]
@grshane those are because we had built those components prior to the icon component being built and so they were commented out until that was implemented. I think we can put in a follow up ticket to go in and connect those pieces

**Comment by himerus** [comment]
Yeah, that. And I just removed the "broken" story for now so it didn't show up.

**Comment by grshane** [comment]
Works for me

Gregg Shanefelt
Software Architect

...
c. 724.244.4613
s. github | linkedin

Pittsburgh, Pennsylvania

**Review by grshane — APPROVED** [review]

**Pull request merged**
